### ISSUE TITLE
 Mod install error

### ISSUE THREAD

**Issue by Josea2002** [TheOddler/FactorioWorld#15]
When I try to install the mod from the "Mods" menu, it seems to install correctly, but when the game is restarted, Factorio does not load the mod. (Like if it wasn't installed)
![image](https://user-images.githubusercontent.com/63645270/86848996-653e8180-c085-11ea-83f4-b966e0ebb2ca.png)

**Comment by TheOddler** [comment]
Hmm, very strange problem. And this is the only mod you have this problem with?

I'll take a look at it tonight after work.

As a reminder to myself, originally the problem was reported here: https://mods.factorio.com/mod/factorio-world/discussion/5a5f1b0dadcc441024d75c8f#post-12

**Comment by TheOddler** [comment]
Ok, I re-uploaded the latest version. It seems I used a zip compression that isn't supported by the game, and that made it fail to load.

Should be good now! Could you see if you can download the new zip? It has the same version number though, maybe I should bump the version number so people don;t get confused. What does your game say? Does it say the mod was updated?

**Comment by Josea2002** [comment]
Perdón amigo, no pude abrir el traductor, hice funcionar el mod pero actualmente la ultima versión que actualizaste, sigue sin poder aplicarse con éxito.
![image](https://user-images.githubusercontent.com/63645270/86982387-7a87de80-c15f-11ea-8da9-ce7a9e616452.png)
La ultima versión instalada correctamente es la 0.18.0

**Comment by TheOddler** [comment]
There should be a version 0.18.2, I just updated that. You can just get it from website itself:

![image](https://user-images.githubusercontent.com/1831376/87008566-41ce2080-c1c4-11ea-8a73-2d74b3e909de.png)

**Comment by TheOddler** [comment]
@Josea2002 Did it work?

**Comment by TheOddler** [comment]
I'm assuming this was fixed and will be closing this ticket now. If it was not fixed, please reopen.
