### ISSUE TITLE
runs on surface other than nauvis

### ISSUE THREAD

**Issue by misterbigstuff** [TheOddler/FactorioWorld#16]
please limit it to nauvis, it breaks SE otherwise.

**Comment by TheOddler** [comment]
Aha! I indeed didn't think of other surfaces. Shouldn't be too hard to change. I'll look into it.

Thanks for reporting this!

**Comment by misterbigstuff** [comment]
`on_chunk_generated` event.surface should be 'nauvis'.

**Comment by TheOddler** [comment]
I just released a new version, it now checks for "nauvis", and I also added a dirty hardcoded way of safeguarding the spaceship, so it doesn't sink.
