### ISSUE TITLE
Update for Factorio 0.15?

### ISSUE THREAD

**Issue by StephanSteinert** [TheOddler/FactorioWorld#2]

**Comment by TheOddler** [comment]
Hey, I'm not sure if this will work, but I quicly created an (untested) fix that might possible work maybe.

It's in a new branch here in github: https://github.com/TheOddler/FactorioWorld/tree/0.15-Update Just download it as a zip, and see if that works for 0.15. If not I'll update the mod properly later, but that will take some time.

Again, this fix is untested, let me know if it works ;)

**Comment by TheOddler** [comment]
I just took a little time to test the fix, and it seems to work fine. I uploaded the updated version to mods.factorio.com. Have fun with it!

**Comment by StephanSteinert** [comment]
Thank you 🥇

**Comment by TheOddler** [comment]
No problem :D 

Btw, if you ever have cool screenshots of bases on this map, I would love to add them to the mod description ;)

Have fun!
