### ISSUE TITLE
Bug: water edge 

### ISSUE THREAD

**Issue by DjSapsan** [TheOddler/FactorioWorld#23]
I have the latest version of the mod. Half of Europe is broken and have water edge
![image](https://user-images.githubusercontent.com/12209464/137596338-bb324bef-9729-414a-a3e5-1275cf36219a.png)

**Comment by DjSapsan** [comment]
So looks like the scale has changed during the gameplay

**Comment by Echo51** [comment]
Hi. I've experienced something similar on an older save i created last year, and picked up again recently. It does seem like Scale or positioning of the world changed somewhere along the way for my save too.

**Comment by TheOddler** [comment]
Ah yea, there have been changes to the map and generation algorithm in one of the latest updates by @HySpeed , might have to do with that.

**Comment by TheOddler** [comment]
So sadly this is the result of some changes in the generation algorithm. We'll make sure next time, if there are changes like this, to update the major version number of this mod to reflect that there are breaking changes essentially.
@HySpeed plase make sure to do this too if you make changes that affect the generation algorithm.

And with that, I'll close the ticket. Sorry for the inconvenience!
