### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by massivedynamic1000** [TheOddler/FactorioWorld#25]
I love your mod, I've been fiddling with settings trying to get a "perfect" world map so that it looks like a real wall type map of the world. I actually have achieved the look that I want, but only for screenshot purposes. Because (it seems to me) the world generates centered around the starting area. This means that when I scale the map to scale 1, I have to spawn off the west coast of Africa to get a perfect non-repeating map at the perfect map size, but unfortunately, my spawn point ruins the map by adding a peninsula tagged onto the west coast of Africa.

Can you give me any advice as to how I could do this better?

So to be clear, is it possible to have settings that allow for 1 full map of the world at a specific map size based on the scale factor so that player spawn does not affect the look of the complete revealed map and the complete map looks as it does here.

![Factorio World Map](https://user-images.githubusercontent.com/110350035/182039228-bbe1cbc4-791b-4d09-9035-d1523e47b98a.png)
.

**Comment by HySpeed** [comment]
Hi @massivedynamic1000 ,
If you check my latest version of Cities of Earth 3, you'll find that Nexela has re-worked the map generation that will allow you to choose your spawn point and have a full map.
Also, I include a version of the world map where the major continents are swapped, so you could build a small bridge connecting Russia and Alaska.

**Comment by massivedynamic1000** [comment]
Yes! That is exactly what I am looking for. Thanks.

**Comment by TheOddler** [comment]
So since this seems to be solved, I'll close this ticket :D Glad it was solved so quick!
