### ISSUE TITLE
Suggestion: FactorioWorld with AlienBiomes Mod

### ISSUE THREAD

**Issue by Tomirad** [TheOddler/FactorioWorld#4]
Have you thought about using AlienBiomes modifications to create a world with more land?
https://mods.factorio.com/mods/Earendel/alien-biomes

**Comment by TheOddler** [comment]
I was not aware of that mod, and damn it looks cool. But sadly I'm not really playing factorio anymore lately (lost a week to it a month ago, so trying to spend some time on other stuff :P). So for now this mod will stay as is. You are welcome to use my code though :D Just make sure you open-source your own code aswell.
