### ISSUE TITLE
Push to Mod Portal?

### ISSUE THREAD

**Issue by HySpeed** [TheOddler/FactorioWorld#6]
Hi,

Can you post version 0.16.1 to the Factorio Mod Portal?

My mod needs that version for the settings.lua features.

thanks,
jon
(https://github.com/HySpeed/CitiesOfEarth)

**Comment by TheOddler** [comment]
Hi, I updated the version on the mod portal ;)

I love that you made your own fix for the spawn points! I should really have done that myself, but never got around to it. If you prefer you can also put it directly in this mod, and I'll pull it in via a pullrequest. Though it's up to you. Eventually I'll get around to adding it here to anyway, but not sure when I'll make some time for it.

Thanks!
