### ISSUE TITLE
Issue with Landfill

### ISSUE THREAD

**Issue by Eriffe** [TheOddler/FactorioWorld#7]
Every time i try use landfill only turn water to light blue.. i cant use landfill with mod on..

**Comment by TheOddler** [comment]
That's because I created this world in my image, and you are not allowed to just change my legacy!

No, I have no clue why this is. I don't have the mod installed myself at the moment, but I'll check. Thanks for reporting this!

**Comment by Eriffe** [comment]
I found later, this is a problem with nicefill mod... sorry..

**Comment by TheOddler** [comment]
Aha, no problem whatsoever :D
