### ISSUE TITLE
update to Factorio 0.17

### ISSUE THREAD

**Issue by maylortaylor** [TheOddler/FactorioWorld#8]
I really love this mod; however, I found it just before the 0.17 update. Is there any hopes of you updating this to work with 0.17?
I'm a web developer and I could help if pointed in the right direction.

**Comment by TheOddler** [comment]
Done!

You were lucky all I had to do is change the info.json file to say "sure this works in 0.17", and now it does.

Note that the mod only uses a subset of the terrain types, as it was made before they added a whole bunch of new ones, and I never got around to adding those in. But, other than that it seems to work.
